# -*- coding: utf-8 -*-
"""twitter_sentiment_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1APC-g8aSzpf_AcUIpDkLWKCRKBJ-CG9G
"""

!ls

!wget https://github.com/futurexskill/ml-model-deployment/raw/main/tfidfmodel.pickle

!wget https://github.com/futurexskill/ml-model-deployment/raw/main/textclassifier.pickle

!ls

import tweepy

consumer_key='tTSpcdoqk2hPeaTWjKrrMd3jG'
consumer_secret='RX62QGkaWrgqP8xQT6Kx1dfexXYGQCACZtW3qrqrWSjVzreMca'
access_token ='1156204423539912704-17tCaEtatgGqPNvS7GXGY4NLE0avt2'
access_secret='jYqZNbGnUE7psVAqKsxsjSctKbL1P6r9U6o1mMYKYbdDr'

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_secret)

api = tweepy.API(auth,timeout=20)

tweet_text = 'vaccine';

tweets_list = []

for status in tweepy.Cursor(api.search,q=tweet_text,lang='en',result_type='recent').items(500):
        tweets_list.append(status.text)

len(tweets_list)

tweets_list[30]

import re

for i in range(len(tweets_list)):
  # get each tweet
  tweet = tweets_list[i]
  tweet = tweet.lower()
  # remove junk characters 
  tweet = re.sub(r'\W',' ',tweet)
  # remove one or more space
  tweet = re.sub(r'\s+',' ',tweet)
  # Remove all characters except a to z or A to Z and replace them with a space
  tweet = re.sub('[^a-zA-Z]',' ',tweet)
  # store the clean tweet back in the list
  tweets_list[i] = tweet

tweets_list[30]

import pickle

with open('textclassifier.pickle','rb') as file:
    classifier = pickle.load(file)

with open('tfidfmodel.pickle','rb') as file:
    tfidf = pickle.load(file)

positive_tweet = 0
negative_tweet = 0

for tweet in tweets_list:
  sentiment = classifier.predict(tfidf.transform([tweet]).toarray())
  if sentiment[0] == 1:
    positive_tweet += 1
  else:
    negative_tweet += 1

positive_tweet

negative_tweet

